[package]
name = "AMirror"
version = "0.1.0"
edition = "2021"

[dependencies]
rusb = "0.9.4"
mpv = "0.2"
rodio = "0.19.0"
openssl-sys = "0.9"
openssl = "0.10"
protobuf = "3.7.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
