; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATmega4808]
platform = atmelmegaavr
board = ATmega4808
framework = arduino

upload_protocol = serialupdi

board_build.f_cpu = 20000000L

lib_deps = 
	file:///home/aidan/Arduino/libraries/elapsedMillis
	file:///home/aidan/Arduino/libraries/Vector/src
	file:///home/aidan/Arduino/libraries/arduino-mcp2515-master
